##===- lib/Transforms/irs_tagged_memory/Makefile -----------*- Makefile -*-===##
#
#                     The LLVM Compiler Infrastructure
#
# This file is distributed under the University of Illinois Open Source
# License. See LICENSE.TXT for details.
#
##===----------------------------------------------------------------------===##

LEVEL = ../../..
LIBRARYNAME = irs_tagged_memory
LOADABLE_MODULE = 1
USEDLIBS =

include $(LEVEL)/Makefile.common

